[package]
name = "bedelli"
version = "0.1.0"
authors = ["Zekeriya Koc <zekzekus@gmail.com>"]

[dependencies]
rand = "*"
clippy = "*"

[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs"
